# -*- coding: utf-8 -*-
"""InventoryManagementSystem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_TYoINb3a6fR40gz3mJdCUco0X_040Bw
"""

import json
import time

fd=open("records.json","w")
products={'1001':{"name":"browniw","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
          '1002':{"name":"Chew Chew","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
          '1003':{"name":"ChocLife","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"} ,
         '1004':{"name":"ChocLive","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1005':{"name":"ChocoBuds","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1006':{"name":"ChocoCream","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1007':{"name":"ChocoDelight","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1008':{"name":"KitKat","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1009':{"name":"Dairy Milk","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1010':{"name":"5Star","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1011':{"name":"Perk","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1012':{"name":"ChocoDream","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1013':{"name":"ChocoFantasy","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
          '1014':{"name":"ChocoFate","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1015':{"name":"Chocoholics","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1016':{"name":"ChocoLasting","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1016':{"name":"ChocolateCeleb","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1017':{"name":"ChocolateCheer","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1018':{"name":"ChocoLux","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1019':{"name":"ChocoLuxe","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1020':{"name":"ChocoPals","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1021':{"name":"ChocoChoco","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1022':{"name":"ChocoChips","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1023':{"name":"ChocoSmiles","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1023':{"name":"SweetCandy","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1024':{"name":"SweetMarie","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1025':{"name":"SweetDesigns ","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1026':{"name":"vannilla milk","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1027':{"name":"pista milk","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1028':{"name":"blackcurrent milk","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1028':{"name":"mixed juice","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"},
         '1030':{"name":"Mojito","price":50,"quantity":100,"ex_date":"19-9-2022","maf_date":"11-8-2021"}}
jformat=json.dumps(products)
fd.write(jformat)
fd.close()

fd=open("records.json","r")
txt=fd.read()
fd.close()
products=json.loads(txt)

"""Purchasing the product"""

print("------------MENU------------")
print("product_id    product_name",end="\n\n")
for i in products.keys():
    print(i,"        ",products[i]["name"])

"""Product id and quantity"""

user_id=input("Enter the product id- :")
quantity=int(input("Enter The Quantity- :"))
product_id=products.keys()

if (user_id not in product_id):
    print("It's wrong Product Id ")
    
    
    
flag=0
if(products[user_id]["quantity"]<quantity):
    print("The available quantity is :" ,products[user_id]["quantity"])
    ans=int(input("Do you want to take these quantity(1-yes/0-No)"))
    if(ans):
        print("The bill is processed!!")
        quantity=products[user_id]["quantity"]
        
    else:
        flag=1
        print("choose any other product")
  
products[user_id]["quantity"]-=quantity

"""Printing the bill"""

if(flag==0):
    print("----------Bill----------",end=" ")
    print("Time :",time.ctime(),"--------------------")
    print("Product :",products[user_id]["name"])
    print("Quanity :",quantity)
    print("Price :",products[user_id]["price"])
    print("Billing Amount :",products[user_id]["price"]*quantity)
    print("---------------------------------------------------------------------------------")

"""Adding the product"""

product_id=products.keys()
new_id=input("Enter the id of the product-")
if new_id in product_id:
    qun=int(input("Enter the product Quantity-"))
    products[new_id]["quantity"]+=qun
    print("Qunatity Added")

fd = open("records.json", 'r')
    txt = fd.read()
    data = json.loads(txt)
    fd.close()
    print("Enter New Product ID :- ")
    id = input()
     
    if id not in products.keys():
        print("Enter Product Name :- ")
        name = input()
         
        print("Enter Price of Product(price for product quantity as 1) :- ")
        price = input()
         
        print("Enter Quantity of Product :- ")
        quantity = input()
         
        print("Enter The manufacturing date on Which Product is Added in Inventory :- ")
        maf_date = input()

        print("Enter the expiration date of the product: ")
        ex_date= input()
         
        data[id] = {'name': name, 'price': price,
                    'quantity': quantity, 'maf_date': maf_date, 'ex_date': ex_date}
        print("Please Press '0' to Add New Attributes\
        /Properties of Product or Press '1' to Continue :- ")
        z = int(input())
         
        if(z == 0):
            print("Enter Number of New Attributes/Properties of Product :- ")
            n = int(input())
             
            for i in range(n):
                print("Enter Attribute Name That you Want To Add :- ")
                nam = input()
                print("Enter The "+str(nam)+" of Product :- ")
                pro = input()
                data[id][nam] = pro
        print("Product ID "+str(id)+" Added Successfully...!!!")
         
    else:
        print("The Product ID you Have Entered Is Already Present\
        t in DataBase Please Check...!!!")
    js = json.dumps(data)
    fd = open("data.json", 'w')
    fd.write(js)
    fd.close()

fd=open("records.json","w")
jformat=json.dumps(products)
fd.write(jformat)
fd.close()